### ISSUE TITLE
Stops scraping until manually reloaded

### ISSUE THREAD

**Issue by Muppetteer** [troykelly/hacs-amberelectric#3]
I installed this fine through HACS but have found that it will intermittently stop scraping and the various prices get stuck at the last good value. I can resolve this by manually reloading the integration (Configuration > Integrations > Amber dot menu > Reload) but it will inevitably get stuck again some time later. Is there a log file anywhere that I can look at to try to work out why this might be happening?

![amber-stuck](https://user-images.githubusercontent.com/13409539/112067214-cf6b6800-8bbb-11eb-8087-790da95f5cc4.png)

**Comment by Muppetteer** [comment]
The previous pic showed right after I reloaded the integration and started it working again. This one shows how it worked for a couple of hours then got stuck again and has not updated for four hours.

![amber-stuck-again](https://user-images.githubusercontent.com/13409539/112094014-8da7e500-8bee-11eb-941c-2ea8840c410d.png)

**Comment by troykelly** [comment]
I can see the behavior as well, thank you for creating the issue.
I have an idea that it might be after the api is unavailable for greater than the retry timeout.
'will see if we can get it resolved.
