### ISSUE TITLE
API BFF seems to be retired

### ISSUE THREAD

**Issue by mattclar** [troykelly/hacs-amberelectric#4]
I spoke with the amber electric crew a while back and they said they were going to retire the api-bff endpoint sometime soon.
Given that the component is no longer able to load and I get an error indicating the domain no longer resolves I think this has happened.
Unfortunately this wrecks this integration!

**Comment by troykelly** [comment]
I will have to rebuild... I just have to find some time in the day!

**Comment by pjmbarlick** [comment]
Thanks Troy...Good luck with the rebuild and thanks for your efforts so far...

**Comment by OmgImAlexis** [comment]
I'm going to take a guess that Amber will suggest devs just use their graphql endpoint.

https://backend.amberelectric.com.au/graphql

**Comment by daffster** [comment]
New API!
https://github.com/amberelectric/public-api/discussions

**Comment by troykelly** [comment]
Apologies for the delay @pjmbarlick @OmgImAlexis @daffster - never got any time to get to this.
Luckily - there is a much better integration [over here](https://github.com/madpilot/hass-amber-electric).
